arm_planning_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - base_joint
    - mid_joint_1
    - mid_join_2
    - wrist_joint
    - hand_flip
    - claw_1
  gains:
    base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    mid_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    mid_join_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    hand_flip:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    claw_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - claw_1
    - claw_3
    - claw_2
    - claw_4
  gains:
    claw_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    claw_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    claw_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    claw_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1